/**
 * CPOO Server API
 * This is a prototype of CPOO Project\'s front/back API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * New message information
 */
export interface NewMessageDTO { 
    to: string;
    type: string;
    body: string;
}

