/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



package org.openapitools.client.api;

import okhttp3.OkHttpClient;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.UserDTO;

/**
 * API tests for AdministrationApi
 */
@SuppressWarnings("KotlinInternalInJava")
public class AdministrationApiTest {

  private final AuthenticationApi authenticationApi = new AuthenticationApi();

  private final AdministrationApi administrationApi = new AdministrationApi();

  @BeforeEach
  public void init() {

    // Simulate the behavior of a web browser by remembering cookies set by the server
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    OkHttpClient okHttpClient = builder.cookieJar(new MyCookieJar()).build();
    ApiClient apiClient = new ApiClient(okHttpClient);
    authenticationApi.setApiClient(apiClient);
    administrationApi.setApiClient(apiClient);
  }

//  @Test
//  public void userLoginDeleteTest() throws ApiException {
//
//    // Delete the test account if exists
//    authenticationApi.userSigninPost(new UserDTO().login("admin").password("admin"));
//    try {
//      administrationApi.userLoginDelete("test");
//    }
//    catch (ApiException e) {
//      Assertions.assertEquals(HttpStatus.SC_NOT_FOUND, e.getCode());
//    }
//    authenticationApi.userSignoutPost();
//
//    // Sign up a test user
//    UserDTO testUser = new UserDTO().login("test").password("test");
//    authenticationApi.userSignupPost(testUser);
//
//    // Sign in as the test user
//    authenticationApi.userSigninPost(testUser);
//
//    // Deleting the test account without admin rights should fail with FORBIDDEN
//    try {
//      administrationApi.userLoginDelete("test");
//      Assertions.fail();
//    }
//    catch (ApiException e) {
//      Assertions.assertEquals(HttpStatus.SC_FORBIDDEN, e.getCode());
//    }
//
//    // Sign is as the admin
//    authenticationApi.userSignoutPost();
//    authenticationApi.userSigninPost(new UserDTO().login("admin").password("admin"));
//
//    // Deleting the test account with admin rights should work
//    administrationApi.userLoginDelete("test");
//  }
}


